import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.scss";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const museoCyrl = localFont({
  src: "../assets/fonts/Museo Cyrl/museo_cyrl.otf",
  variable: "--font-museo-cyrl",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${museoCyrl.variable}`}>
        {children}
      </body>
    </html>
  );
}
